fm_elfinder:
    instances:
        default:
            locale: '%stof_doctrine_extensions.default_locale%'
            editor: ckeditor
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: uploads
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']

